### ISSUE TITLE
ruuvitag in openplotter, signalk/instrumentpanel

### ISSUE THREAD

**Issue by verschuijten** [vokkim/signalk-ruuvitag-plugin#11]
I want to install ruuvitag in signalk/instrumentpanel on rpi. What are the steps? I can install the plugin app but after that no glue to go further. Plugin is installed but can't access.
thanks, 
John

**Comment by ghost** [comment]
What do you mean with can't access?

Instructions for the very straight forwarded installation process is here: [https://github.com/vokkim/signalk-ruuvitag-plugin/blob/master/README.md](url)

**Comment by verschuijten** [comment]
Hi MichelleWhy,

Do I need to follow step 0? Because i get an error.
Step 3, i don't know what happens but nothing opens so i can't access anything.

Kind regards,
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by verschuijten** [comment]
This is the error what i see. [Image]

Kind regards,
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
Yes, you need to follow the installation through all steps including 0.
Step 3 says it will take a few minutes. And that's what it did for me too.
Once detection is complete, it will fill automatically with a configuration menu. If it doesn't, make sure that the plugin is activated. Then restart the server or reboot. Next open the plugin again and wait as per Step 3.

This is roughly how it should look like (except for source name and location):
<img width="1100" alt="Bildschirmfoto 2021-01-21 um 13 43 29" src="https://user-images.githubusercontent.com/48654848/105353295-58334b00-5bef-11eb-9e91-5890731fabc3.png">

**Comment by verschuijten** [comment]
Okay, first time i installed the plugin first.
When it was not possible to open i deleted but still step 0 is not possible. Even after fresh start not possible.
What do i wrong?

Kind regards,
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
John, in order to give more detailed help, we need more detailed info.
What do you mean with "step 0 is not possible"? What did you delete? Do you have some screenshots or output from your Pi console? Anything from /var/log/syslog?

**Comment by verschuijten** [comment]
[Image]

Kind regards,
John
________________________________
Van: MichelleWhy <notifications@github.com>
Verstuurd: donderdag 21 januari 2021 15:04
Aan: vokkim/signalk-ruuvitag-plugin
Cc: verschuijten; Author
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)


John, in order to give more detailed help, we need more detailed info.
What do you mean with "step 0 is not possible"? What did you delete? Do you have some screenshots or output from your Pi console? Anything from /var/log/syslog?

**Comment by verschuijten** [comment]
I tried to install the plugin first,  was not working,  then I tried to do step 0: running on Linux:
I got the message in the screenshot which i sent you in the previous mail.
Then I deleted the plugin in the hope that i could go back to step 0. But the message which appears stays the same.
Do i have to do something more?
I am not so experienced and was just looking for a solution to make it work.

Kind regards,
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
John, unfortunately the image(s) you sent came not through. Sorry.

**Comment by verschuijten** [comment]
[Image]
And now?

Kind regards,
John
________________________________

**Comment by ghost** [comment]
Nope. Simply drag and drop the image into the comment section.

<img width="846" alt="Bildschirmfoto 2021-01-21 um 15 15 09" src="https://user-images.githubusercontent.com/48654848/105362704-7dc65180-5bfb-11eb-80e7-c5149f989f76.png">

**Comment by verschuijten** [comment]
it is a png file, don't know how to change this. but I see it in my previous mails


Met vriendelijke groet,

John Verschuijten
mob: 0031(0)615227015
email: verschuijten@hotmail.com
http://www.ashaatsea.com  <http://www.ashaatsea.com>
<http://www.juiceplus.nl/+jv014879>
Call
Send SMS
Call from mobile
Add to Skype
You'll need Skype CreditFree via Skype

________________________________
Van: MichelleWhy <notifications@github.com>
Verzonden: donderdag 21 januari 2021 15:16
Aan: vokkim/signalk-ruuvitag-plugin <signalk-ruuvitag-plugin@noreply.github.com>
CC: verschuijten <verschuijten@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)


Nope. Simply drag and drop the image into the comment section.

[Bildschirmfoto 2021-01-21 um 15 15 09]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48654848%2F105362704-7dc65180-5bfb-11eb-80e7-c5149f989f76.png&data=04%7C01%7C%7Ceb745b6d4c9b4228733a08d8be1722bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637468353854175841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E1AVFutTAyOaGhJgVAkbK%2FDtcEAPLzVzafEVu7XxQo4%3D&reserved=0>

**Comment by verschuijten** [comment]
[cid:image004.jpg@01D6F00D.0B965150]


Van: John Verschuijten <verschuijten@hotmail.com>
Verzonden: Thursday, January 21, 2021 3:31:13 PM
Aan: vokkim/signalk-ruuvitag-plugin <reply@reply.github.com>
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)

it is a png file, don't know how to change this. but I see it in my previous mails


Met vriendelijke groet,

John Verschuijten
mob: 0031(0)615227015
email: verschuijten@hotmail.com
http://www.ashaatsea.com  <http://www.ashaatsea.com>
Call
Send SMS
Call from mobile
Add to Skype
You'll need Skype CreditFree via Skype


Van: MichelleWhy <notifications@github.com>
Verzonden: donderdag 21 januari 2021 15:16
Aan: vokkim/signalk-ruuvitag-plugin <signalk-ruuvitag-plugin@noreply.github.com>
CC: verschuijten <verschuijten@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)


Nope. Simply drag and drop the image into the comment section.

[Bildschirmfoto 2021-01-21 um 15 15 09]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48654848%2F105362704-7dc65180-5bfb-11eb-80e7-c5149f989f76.png&data=04%7C01%7C%7Ceb745b6d4c9b4228733a08d8be1722bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637468353854175841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E1AVFutTAyOaGhJgVAkbK%2FDtcEAPLzVzafEVu7XxQo4%3D&reserved=0>

**Comment by verschuijten** [comment]
Hello,

Hopefully you have received the Terminal picture now.
I started complete new with NOOBS openplotter Basic.
Still no results. Is the problem maybe because I'm working in basic and not in advanced?
I tried many ways but like the other plugins no config appears in the ruuvitag plugin.
I followed your link step by step but the answer is what you see in the picture. ( which you hopefully can see now)

What am I doing wrong?
I work on a new rpi 4, 8Gb.

Kind regards,
John Verschuijten

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
From: John Verschuijten <verschuijten@hotmail.com>
Sent: Thursday, January 21, 2021 4:50:28 PM
To: vokkim/signalk-ruuvitag-plugin <reply@reply.github.com>
Subject: RE: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)


[cid:image004.jpg@01D6F00D.0B965150]





Van: John Verschuijten <verschuijten@hotmail.com>
Verzonden: Thursday, January 21, 2021 3:31:13 PM
Aan: vokkim/signalk-ruuvitag-plugin <reply@reply.github.com>
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)



it is a png file, don't know how to change this. but I see it in my previous mails




Met vriendelijke groet,

John Verschuijten

mob: 0031(0)615227015
email: verschuijten@hotmail.com

http://www.ashaatsea.com  <http://www.ashaatsea.com>

Call

Send SMS

Call from mobile

Add to Skype

You'll need Skype CreditFree via Skype





Van: MichelleWhy <notifications@github.com>
Verzonden: donderdag 21 januari 2021 15:16
Aan: vokkim/signalk-ruuvitag-plugin <signalk-ruuvitag-plugin@noreply.github.com>
CC: verschuijten <verschuijten@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [vokkim/signalk-ruuvitag-plugin] ruuvitag in openplotter, signalk/instrumentpanel (#11)



Nope. Simply drag and drop the image into the comment section.

[Bildschirmfoto 2021-01-21 um 15 15 09]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48654848%2F105362704-7dc65180-5bfb-11eb-80e7-c5149f989f76.png&data=04%7C01%7C%7Ceb745b6d4c9b4228733a08d8be1722bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637468353854175841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E1AVFutTAyOaGhJgVAkbK%2FDtcEAPLzVzafEVu7XxQo4%3D&reserved=0>

**Comment by ghost** [comment]
Hi,
still not seeing any images uploaded from you. And I don't know open plotter basic. So can't help on that.
The config in the ruuvitag plugin only appears when the plugin received the Tag.

I'm really trying to help here but it lacks of information as requested above. Maybe some else can help.

**Comment by verschuijten** [comment]
Thanks that you're so patient with me.
That's really weird. I sent you pictures in .png format and last one was a .jpg format.
Even one in the beginning made by my phone.
Anyway, de Rpi sees the ruuvitag by Bluetooth so Bluetooth is working.  Only not in the program. But maybe you can explain how I can do " give node process permissions to scan BLE devices: I typed after" $ sudo setcap cap_net_raw+eip $(eval readlink -f 'which node') " if I type this right in the Terminal I get the message: failed to set capabilities on file

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by verschuijten** [comment]
Previous mail was sent to early,  was not finished yet but my fingers were to big,  haha

Thanks that you're so patient with me.
That's really weird. I sent you pictures in .png format and last one was a .jpg format.
Even one in the beginning made by my phone.
Anyway, de Rpi sees the ruuvitag by Bluetooth so Bluetooth is working. Only not in the program. But maybe you can explain how I can do " give node process permissions to scan BLE devices: I typed after" $ sudo setcap cap_net_raw+eip $(eval readlink -f 'which node') " if I type this right in the Terminal I get the message: failed to set capabilities on file 'home/pi/which' (no such file or directory) The value of the capability argument os not permitted for a file.  Or the file is not a regular (non-symlink) file

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by verschuijten** [comment]
I try to get it installed in openplotter which works with signalk. With this I can show the values on a webapp @signalk/instrumentpanel.
But somehow i don't manage to get the plugin  config recognise the tag.
I can't find anymore instructions on the web or in github

Kind regards,
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
This really goes beyond my knowledge.
I think there is something not as expected with your node.js installation or home directory. This has nothing to do with the plugin itself.

I suggest you search the internet for the error message or get help in the openplotter forum or from where you got the noobs basic image.

**Comment by verschuijten** [comment]
Okay,  I will look further. Maybe i have an idea

Thanks so far.
John

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
