### ISSUE TITLE
ENODEV error when trying to configure

### ISSUE THREAD

**Issue by seabits-steve** [vokkim/signalk-ruuvitag-plugin#14]
Trying to setup three Ruuvitag with my Signal K server and getting an error about what looks like a missing device. Not sure where to start to debug this. 

`Feb 22 12:53:19 r signalk-server[4118]: ruuvitag:no configuration data
Feb 22 12:53:19 r kernel: [  219.229674] Bluetooth: Core ver 2.22
Feb 22 12:53:19 r kernel: [  219.229770] NET: Registered protocol family 31
Feb 22 12:53:19 r kernel: [  219.229775] Bluetooth: HCI device and connection manager initialized
Feb 22 12:53:19 r kernel: [  219.229782] Bluetooth: HCI socket layer initialized
Feb 22 12:53:19 r kernel: [  219.229785] Bluetooth: L2CAP socket layer initialized
Feb 22 12:53:19 r kernel: [  219.229794] Bluetooth: SCO socket layer initialized
Feb 22 12:53:19 r signalk-server[4118]: error starting plugin: Error: ENODEV, No such device
Feb 22 12:53:19 r signalk-server[4118]: Error: ENODEV, No such device
Feb 22 12:53:19 r signalk-server[4118]:     at Hci.init (/home/stevemitchell/.signalk/node_modules/@abandonware/noble/lib/hci-socket/hci.js:114:35)
Feb 22 12:53:19 r signalk-server[4118]:     at NobleBindings.init (/home/stevemitchell/.signalk/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:82:13)
Feb 22 12:53:19 r signalk-server[4118]:     at Noble.get (/home/stevemitchell/.signalk/node_modules/@abandonware/noble/lib/noble.js:72:26)
Feb 22 12:53:19 r signalk-server[4118]:     at new Adapter (/home/stevemitchell/.signalk/node_modules/node-ruuvitag/adapter.js:17:15)
Feb 22 12:53:19 r signalk-server[4118]:     at Object.<anonymous> (/home/stevemitchell/.signalk/node_modules/node-ruuvitag/adapter.js:48:18)
Feb 22 12:53:19 r signalk-server[4118]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Feb 22 12:53:19 r signalk-server[4118]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Feb 22 12:53:19 r signalk-server[4118]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Feb 22 12:53:19 r signalk-server[4118]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Feb 22 12:53:19 r signalk-server[4118]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Feb 22 12:53:19 r signalk-server[4118]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Feb 22 12:53:19 r signalk-server[4118]:     at require (internal/modules/cjs/helpers.js:25:18)
Feb 22 12:53:19 r signalk-server[4118]:     at Object.<anonymous> (/home/stevemitchell/.signalk/node_modules/node-ruuvitag/index.js:1:17)
Feb 22 12:53:19 r signalk-server[4118]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Feb 22 12:53:19 r signalk-server[4118]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Feb 22 12:53:19 r signalk-server[4118]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Feb 22 12:53:19 r signalk-server[4118]: #033[0mPOST /skServer/plugins/ruuvitag/config #033[32m200#033[0m 8.642 ms - 39#033[0m`

**Comment by vokkim** [comment]
Similar to https://github.com/vokkim/signalk-ruuvitag-plugin/issues/5 - no bluetooth device?

**Comment by vokkim** [comment]
This should not crash the entire SignalK server anymore, see `https://github.com/vokkim/signalk-ruuvitag-plugin/commit/d4e7c7cf9843204e9a8569c7c9bfb21faae33280`
