### ISSUE TITLE
Still no Ruuvitag showing up

### ISSUE THREAD

**Issue by seabits-steve** [vokkim/signalk-ruuvitag-plugin#16]
Still trying to get this to work. My Bluetooth adapter had some sort of odd situation for the last issue I opened, but it is working fine and no errors are happening now. 

I have three Ruuvitag and none of them are seen by the plugin. I've followed your installation instructions and can see no errors in the logs. In fact, I see nothing at all in the logs from the plugin other than startup messages. I've tried debug logging as well and don't see anything. 

The tags are showing up in the app on an iPhone and the related computer running the Bluetooth radio is within a foot of that phone and the tags. 

The plugin screen shows nothing other than it is enabled, and a submit button. 

If you prefer to support this plugin in signalk-slack or somewhere else, please advise as so far support has been very challenging.

**Comment by vokkim** [comment]
What operating system and bluetooth adapter are you using? You could try to debug BLE with some other software, I've used `LightBlue` for macOS, `nRF Connect` might work in Windows as well.
