### ISSUE TITLE
Add to installation - or to documentation

### ISSUE THREAD

**Issue by Krecik7** [vokkim/signalk-ruuvitag-plugin#26]
Please, add this information to documentation, or add to install script - that if you want to change units then you have to update baseDeltas.json and add - something similar to this here. And then it will start to work corectly - you can choose units and see something different than Pa or Kelvins in SignalK Instrument Panel :-)
```
[...]
    {
    "context": "vessels.self",
    "updates": [
      {
        "meta": [
          {
            "path": "environment.mesa.srodek.temperature",
            "value": {
              "description": "RuuviTag - temperatura mesa",
              "units": "K",
              "displayName": "Mesa - temp",
              "timeout": 30
            }
          },
          {
            "path": "environment.mesa.srodek.pressure",
            "value": {
              "description": "RuuviTag - ciśnienie atm",
              "units": "Pa",
              "displayName": "Mesa - ciśnienie",
              "timeout": 30
            }
          },
          {
            "path": "environment.mesa.srodek.relativeHumidity",
            "value": {
              "description": "RuuviTag - wilgotność",
              "units": "ratio",
              "displayName": "Mesa - wilgotność",
              "timeout": 30
            }
          }
        ]
      }
    ]
  }
```

**Comment by vokkim** [comment]
SingalK spec uses SI units. User specified display units should be configured in the app used instead.

**Comment by Krecik7** [comment]
You did'nt understand. It's not problem that SignalK uses SI. It's problem, that when you name RuuviTag patch with your own name, then SignalK don't know how to interprete response, and - i.e - in InstrumentPanel there is no option to choose what type is i.e temperture or change Pa to hPa. Because if you put custom name, then your included definitions not working. I didn't check, but i assume that if you put 'inside' or 'outside' , then it works, but if you put name 'myCustomname' in Ruvitag name patch, then it's not working  - SK don't know what to expect from this source.
